//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Inputs Actions/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controles : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""P1"",
            ""id"": ""2cfbd944-e38d-4447-8140-4a0b2ad7689b"",
            ""actions"": [
                {
                    ""name"": ""Andar"",
                    ""type"": ""Value"",
                    ""id"": ""9c7a20c1-6d3d-42db-bc94-831448428abb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interagir"",
                    ""type"": ""Button"",
                    ""id"": ""3285c20f-8c5b-4060-b397-80407386d757"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Correr"",
                    ""type"": ""Button"",
                    ""id"": ""76314763-aaba-48e2-abca-707550f97f06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""d7403011-bc8e-461d-ba3f-03549a9dd838"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fechar"",
                    ""type"": ""Button"",
                    ""id"": ""7037b379-fdcc-45fe-af57-c2c289ec1a42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""2a8ef5bc-035e-4856-83e6-ef82013ce639"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""S"",
                    ""type"": ""Button"",
                    ""id"": ""40002038-24d3-4c3a-9ca6-4f88d3269798"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D"",
                    ""type"": ""Button"",
                    ""id"": ""6ba17693-759e-4788-8c71-b97d13130a08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a7266512-c9e6-41e3-b224-450cf8833916"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""Interagir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f48b7492-eea2-4a36-bf74-04536063661a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Interagir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f71f0349-bf85-41bd-92ca-57187936ac4f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""311ba000-03d2-4d59-a0a8-0cc5b289d525"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Andar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4aac3109-ad1d-40b3-8063-be89cc653aaf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ae0bd4b6-8b35-420f-a0c2-3b4f552d0787"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1c9e9a59-8940-469d-8988-acd38e799997"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""589a8f6f-224b-452f-a181-cb85a5c29028"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""16bd97d6-2e70-4247-a337-7774c5365775"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Correr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e8a2ee9-993b-42bc-96c1-514f81dc8395"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""Correr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f12fc17e-9b77-480b-9343-726c10810716"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af2c19aa-38f9-4a58-8906-a03f61e835b8"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0abdf467-cdf1-45de-847f-89cd5ebfc62e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Fechar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27cb9a80-8c55-4412-a050-2d43c2237db7"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""Fechar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33c9623a-bfea-4ead-82c0-2932be83592e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8406e164-5ad4-42e6-814f-6a22dd7d3a7b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab284e01-b3fc-4440-b5f1-ca9df99e261e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""S"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64394a91-c1e0-4fd5-909c-97a2b363469e"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""S"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3c6b7e6-1472-4a82-8159-fdef342692fb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""080618cf-193b-44dd-8f47-c260aa937dec"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""P2"",
            ""id"": ""4c048a0e-fba4-432d-bed3-4fca434f7ad4"",
            ""actions"": [
                {
                    ""name"": ""Correr"",
                    ""type"": ""Button"",
                    ""id"": ""19de7f12-f5e0-41f3-a82d-469addfda4cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Andar"",
                    ""type"": ""Value"",
                    ""id"": ""ee884448-5dea-4c35-bf08-5eaf42948b36"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interagir"",
                    ""type"": ""Button"",
                    ""id"": ""5042419e-fd9a-4b38-8b7a-cf0ef7062de1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""68a33dc9-9bef-4896-b57e-e10840b0d1c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""J"",
                    ""type"": ""Button"",
                    ""id"": ""9e600e44-9e80-40c1-8b81-854ff3eeefca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""K"",
                    ""type"": ""Button"",
                    ""id"": ""a36e1479-d2ca-4675-8418-3417925ba742"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L"",
                    ""type"": ""Button"",
                    ""id"": ""5201170c-1c26-44cd-9652-8b755235e9df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f6861f60-0752-45cb-b774-be51c6793f96"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Interagir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6edcc3b-23aa-4ae3-aecb-a2cac53058f7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""Interagir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Setas"",
                    ""id"": ""cd7195d1-9c1a-4b07-8ec2-da198e7b0dd9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Andar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""61f26cf4-cf32-480a-b646-0f97ffcdfbbe"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5ea01af2-c2c3-4b40-8705-7c8c5cbf2e1f"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""694c6e9f-22fa-4793-a4ea-3c8da8ed4398"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""039db481-b46a-4622-b29e-10418bee3577"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6c3c918a-5c70-407f-a57c-54f9a0674c56"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""Andar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ec2ef47-a2c6-4721-b032-00755658577b"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Correr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25acb62f-5fcb-4c81-afa9-f6e5d23bad08"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""Correr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ab6049f-18b3-4c77-af0a-0af64a79777f"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1ae1fcc-4e58-4bec-99e9-712ca0783483"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aaf13f89-1cfb-489d-af45-73a2dbc306e4"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""J"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed5294bf-cccb-40a4-809f-e26cc26cccf9"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""J"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1d884ec-6d72-4d77-9917-d07ad86cbb57"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""K"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f04249b8-44fd-47fb-9994-75c15b48110e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""K"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e32f44d-9ea0-4656-8039-27b43927ec83"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88850024-958e-4085-8d5c-ef08886649d6"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Any"",
            ""id"": ""4b7efb8b-b577-480c-9363-bb49bedd6d23"",
            ""actions"": [
                {
                    ""name"": ""AnyKey"",
                    ""type"": ""Button"",
                    ""id"": ""b60140e0-d8b6-4726-bb19-501671c3c85b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""99d878d2-a109-4bc0-acfc-ea00399206bc"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29c921d2-33a4-4a36-8ee2-e555da38f190"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcaff62b-b8df-461e-8d43-2be80c5b6962"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a42ad8dc-416e-4235-a107-de826cab871d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controle"",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8860352e-9830-4d4f-8c73-87ffc0994eb6"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Teclado"",
                    ""action"": ""AnyKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Teclado"",
            ""bindingGroup"": ""Teclado"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controle"",
            ""bindingGroup"": ""Controle"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // P1
        m_P1 = asset.FindActionMap("P1", throwIfNotFound: true);
        m_P1_Andar = m_P1.FindAction("Andar", throwIfNotFound: true);
        m_P1_Interagir = m_P1.FindAction("Interagir", throwIfNotFound: true);
        m_P1_Correr = m_P1.FindAction("Correr", throwIfNotFound: true);
        m_P1_Menu = m_P1.FindAction("Menu", throwIfNotFound: true);
        m_P1_Fechar = m_P1.FindAction("Fechar", throwIfNotFound: true);
        m_P1_A = m_P1.FindAction("A", throwIfNotFound: true);
        m_P1_S = m_P1.FindAction("S", throwIfNotFound: true);
        m_P1_D = m_P1.FindAction("D", throwIfNotFound: true);
        // P2
        m_P2 = asset.FindActionMap("P2", throwIfNotFound: true);
        m_P2_Correr = m_P2.FindAction("Correr", throwIfNotFound: true);
        m_P2_Andar = m_P2.FindAction("Andar", throwIfNotFound: true);
        m_P2_Interagir = m_P2.FindAction("Interagir", throwIfNotFound: true);
        m_P2_Menu = m_P2.FindAction("Menu", throwIfNotFound: true);
        m_P2_J = m_P2.FindAction("J", throwIfNotFound: true);
        m_P2_K = m_P2.FindAction("K", throwIfNotFound: true);
        m_P2_L = m_P2.FindAction("L", throwIfNotFound: true);
        // Any
        m_Any = asset.FindActionMap("Any", throwIfNotFound: true);
        m_Any_AnyKey = m_Any.FindAction("AnyKey", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // P1
    private readonly InputActionMap m_P1;
    private IP1Actions m_P1ActionsCallbackInterface;
    private readonly InputAction m_P1_Andar;
    private readonly InputAction m_P1_Interagir;
    private readonly InputAction m_P1_Correr;
    private readonly InputAction m_P1_Menu;
    private readonly InputAction m_P1_Fechar;
    private readonly InputAction m_P1_A;
    private readonly InputAction m_P1_S;
    private readonly InputAction m_P1_D;
    public struct P1Actions
    {
        private @Controles m_Wrapper;
        public P1Actions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @Andar => m_Wrapper.m_P1_Andar;
        public InputAction @Interagir => m_Wrapper.m_P1_Interagir;
        public InputAction @Correr => m_Wrapper.m_P1_Correr;
        public InputAction @Menu => m_Wrapper.m_P1_Menu;
        public InputAction @Fechar => m_Wrapper.m_P1_Fechar;
        public InputAction @A => m_Wrapper.m_P1_A;
        public InputAction @S => m_Wrapper.m_P1_S;
        public InputAction @D => m_Wrapper.m_P1_D;
        public InputActionMap Get() { return m_Wrapper.m_P1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(P1Actions set) { return set.Get(); }
        public void SetCallbacks(IP1Actions instance)
        {
            if (m_Wrapper.m_P1ActionsCallbackInterface != null)
            {
                @Andar.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnAndar;
                @Andar.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnAndar;
                @Andar.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnAndar;
                @Interagir.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnInteragir;
                @Interagir.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnInteragir;
                @Interagir.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnInteragir;
                @Correr.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnCorrer;
                @Correr.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnCorrer;
                @Correr.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnCorrer;
                @Menu.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnMenu;
                @Fechar.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnFechar;
                @Fechar.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnFechar;
                @Fechar.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnFechar;
                @A.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnA;
                @S.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnS;
                @S.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnS;
                @S.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnS;
                @D.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnD;
                @D.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnD;
                @D.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnD;
            }
            m_Wrapper.m_P1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Andar.started += instance.OnAndar;
                @Andar.performed += instance.OnAndar;
                @Andar.canceled += instance.OnAndar;
                @Interagir.started += instance.OnInteragir;
                @Interagir.performed += instance.OnInteragir;
                @Interagir.canceled += instance.OnInteragir;
                @Correr.started += instance.OnCorrer;
                @Correr.performed += instance.OnCorrer;
                @Correr.canceled += instance.OnCorrer;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @Fechar.started += instance.OnFechar;
                @Fechar.performed += instance.OnFechar;
                @Fechar.canceled += instance.OnFechar;
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @S.started += instance.OnS;
                @S.performed += instance.OnS;
                @S.canceled += instance.OnS;
                @D.started += instance.OnD;
                @D.performed += instance.OnD;
                @D.canceled += instance.OnD;
            }
        }
    }
    public P1Actions @P1 => new P1Actions(this);

    // P2
    private readonly InputActionMap m_P2;
    private IP2Actions m_P2ActionsCallbackInterface;
    private readonly InputAction m_P2_Correr;
    private readonly InputAction m_P2_Andar;
    private readonly InputAction m_P2_Interagir;
    private readonly InputAction m_P2_Menu;
    private readonly InputAction m_P2_J;
    private readonly InputAction m_P2_K;
    private readonly InputAction m_P2_L;
    public struct P2Actions
    {
        private @Controles m_Wrapper;
        public P2Actions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @Correr => m_Wrapper.m_P2_Correr;
        public InputAction @Andar => m_Wrapper.m_P2_Andar;
        public InputAction @Interagir => m_Wrapper.m_P2_Interagir;
        public InputAction @Menu => m_Wrapper.m_P2_Menu;
        public InputAction @J => m_Wrapper.m_P2_J;
        public InputAction @K => m_Wrapper.m_P2_K;
        public InputAction @L => m_Wrapper.m_P2_L;
        public InputActionMap Get() { return m_Wrapper.m_P2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(P2Actions set) { return set.Get(); }
        public void SetCallbacks(IP2Actions instance)
        {
            if (m_Wrapper.m_P2ActionsCallbackInterface != null)
            {
                @Correr.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnCorrer;
                @Correr.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnCorrer;
                @Correr.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnCorrer;
                @Andar.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnAndar;
                @Andar.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnAndar;
                @Andar.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnAndar;
                @Interagir.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnInteragir;
                @Interagir.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnInteragir;
                @Interagir.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnInteragir;
                @Menu.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnMenu;
                @J.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnJ;
                @J.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnJ;
                @J.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnJ;
                @K.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnK;
                @K.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnK;
                @K.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnK;
                @L.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnL;
                @L.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnL;
                @L.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnL;
            }
            m_Wrapper.m_P2ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Correr.started += instance.OnCorrer;
                @Correr.performed += instance.OnCorrer;
                @Correr.canceled += instance.OnCorrer;
                @Andar.started += instance.OnAndar;
                @Andar.performed += instance.OnAndar;
                @Andar.canceled += instance.OnAndar;
                @Interagir.started += instance.OnInteragir;
                @Interagir.performed += instance.OnInteragir;
                @Interagir.canceled += instance.OnInteragir;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @J.started += instance.OnJ;
                @J.performed += instance.OnJ;
                @J.canceled += instance.OnJ;
                @K.started += instance.OnK;
                @K.performed += instance.OnK;
                @K.canceled += instance.OnK;
                @L.started += instance.OnL;
                @L.performed += instance.OnL;
                @L.canceled += instance.OnL;
            }
        }
    }
    public P2Actions @P2 => new P2Actions(this);

    // Any
    private readonly InputActionMap m_Any;
    private IAnyActions m_AnyActionsCallbackInterface;
    private readonly InputAction m_Any_AnyKey;
    public struct AnyActions
    {
        private @Controles m_Wrapper;
        public AnyActions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @AnyKey => m_Wrapper.m_Any_AnyKey;
        public InputActionMap Get() { return m_Wrapper.m_Any; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AnyActions set) { return set.Get(); }
        public void SetCallbacks(IAnyActions instance)
        {
            if (m_Wrapper.m_AnyActionsCallbackInterface != null)
            {
                @AnyKey.started -= m_Wrapper.m_AnyActionsCallbackInterface.OnAnyKey;
                @AnyKey.performed -= m_Wrapper.m_AnyActionsCallbackInterface.OnAnyKey;
                @AnyKey.canceled -= m_Wrapper.m_AnyActionsCallbackInterface.OnAnyKey;
            }
            m_Wrapper.m_AnyActionsCallbackInterface = instance;
            if (instance != null)
            {
                @AnyKey.started += instance.OnAnyKey;
                @AnyKey.performed += instance.OnAnyKey;
                @AnyKey.canceled += instance.OnAnyKey;
            }
        }
    }
    public AnyActions @Any => new AnyActions(this);
    private int m_TecladoSchemeIndex = -1;
    public InputControlScheme TecladoScheme
    {
        get
        {
            if (m_TecladoSchemeIndex == -1) m_TecladoSchemeIndex = asset.FindControlSchemeIndex("Teclado");
            return asset.controlSchemes[m_TecladoSchemeIndex];
        }
    }
    private int m_ControleSchemeIndex = -1;
    public InputControlScheme ControleScheme
    {
        get
        {
            if (m_ControleSchemeIndex == -1) m_ControleSchemeIndex = asset.FindControlSchemeIndex("Controle");
            return asset.controlSchemes[m_ControleSchemeIndex];
        }
    }
    public interface IP1Actions
    {
        void OnAndar(InputAction.CallbackContext context);
        void OnInteragir(InputAction.CallbackContext context);
        void OnCorrer(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnFechar(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnS(InputAction.CallbackContext context);
        void OnD(InputAction.CallbackContext context);
    }
    public interface IP2Actions
    {
        void OnCorrer(InputAction.CallbackContext context);
        void OnAndar(InputAction.CallbackContext context);
        void OnInteragir(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnJ(InputAction.CallbackContext context);
        void OnK(InputAction.CallbackContext context);
        void OnL(InputAction.CallbackContext context);
    }
    public interface IAnyActions
    {
        void OnAnyKey(InputAction.CallbackContext context);
    }
}
